few_shots = [
    {'Question': "Find the client with the highest net worth ?",
     'SQLQuery': "SELECT First_Name, Last_Name FROM client_profile ORDER BY Net_Worth DESC LIMIT 1;",
     'SQLResult': "Result of the SQL query",
     'Answer': "300000"},
    {'Question': "What is the age of Alok Desai?",
     'SQLQuery': "SELECT (strftime('%Y', 'now') - strftime('%Y', Date_of_Birth)) - (strftime('%m-%d', 'now') < strftime('%m-%d', Date_of_Birth)) AS Age FROM client_profile WHERE TRIM(LOWER(First_Name)) = 'Alok' WHERE TRIM(LOWER(Last_Name)) = 'Desai';",
     'SQLResult': "Result of the SQL query",
     'Answer': "49"},
    {'Question': "Get the contact information of all clients living in Texas",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM clients WHERE State = 'Texas';",
     'SQLResult': "Result of the SQL query",
     'Answer': "emai@id.com, secondemail@id.com"},
    {'Question': "Retrieve the average net worth of clients based on their marital status",
     'SQLQuery': "SELECT Marital_Status, AVG(Net_Worth) AS Average_Net_Worth FROM clients GROUP BY Marital_Status;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Give me the net worth of the client with the name 'Sarah Brown'",
     'SQLQuery': "SELECT Net_Worth FROM clients WHERE TRIM(LOWER(First_Name)) = LOWER('Sarah') WHERE TRIM(LOWER(Last_Name)) = LOWER('Brown');",
     'SQLResult': "Result of the SQL query",
     'Answer': "60000"},
    {'Question': "How many dependents does John Doe have?",
     'SQLQuery': "SELECT Dependents FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = LOWER('John') WHERE TRIM(LOWER(Last_Name)) = LOWER('Doe');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "who is alok desai's wife?",
     'SQLQuery': "SELECT First_Name, Last_Name FROM family_members WHERE clientID = (select clientID from client_profile WHERE TRIM(LOWER(First_Name)) = LOWER('Alok') WHERE TRIM(LOWER(Last_Name)) = LOWER('Desai') LIMIT 1);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members of Alok Desai.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Alok' WHERE TRIM(LOWER(Last_Name)) = LOWER('Desai'));",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of all assets for clients living in North Carolina?",
     'SQLQuery': "SELECT SUM(Value) FROM Financial_Assets WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = LOWER('North Carolina'));",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the contact information for clients with more than 2 dependents.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Dependents > 2;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average amount of liabilities for clients who are married?",
     'SQLQuery': "SELECT AVG(Amount) FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Marital_Status = LOWER('Married'));",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all investment types held by Michael Williams.",
     'SQLQuery': "SELECT Investment_Type FROM Investment_Portfolio WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = LOWER('Michael') WHERE TRIM(LOWER(Last_Name)) = LOWER('Williams'));",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many transactions did Alok Desai make in 2023?",
     'SQLQuery': "SELECT COUNT(*) FROM Financial_Transactions WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = LOWER('Alok') WHERE TRIM(LOWER(Last_Name)) = LOWER('Desai')) AND Date BETWEEN '2023-01-01' AND '2023-12-31';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total net worth of all clients?",
     'SQLQuery': "SELECT SUM(Net_Worth) FROM Client_Profile;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients whose profession is 'Doctor'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Profession = 'Doctor';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the financial goals of Jane Smith.",
     'SQLQuery': "SELECT Financial_Goals FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = LOWER('Jane') WHERE TRIM(LOWER(Last_Name)) = LOWER('Smith');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all financial assets of John Doe.",
     'SQLQuery': "SELECT * FROM Financial_Assets WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = LOWER('John') WHERE TRIM(LOWER(Last_Name)) = LOWER('Doe'));",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many clients are single?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Marital_Status = LOWER('Single');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of investments for clients living in Ohio?",
     'SQLQuery': "SELECT SUM(Amount) FROM Investment_Portfolio WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Ohio');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients who have no dependents.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Dependents = 0;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the average net worth of clients living in Texas.",
     'SQLQuery': "SELECT AVG(Net_Worth) FROM Client_Profile WHERE State = 'Texas';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all liabilities for clients with a net worth greater than $1,000,000.",
     'SQLQuery': "SELECT * FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Net_Worth > 1000000);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total number of clients living in North Carolina?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE State = 'North Carolina';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all transactions for clients named 'Emily Johnson'.",
     'SQLQuery': "SELECT * FROM Financial_Transactions WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Emily' WHERE TRIM(LOWER(Last_Name)) = 'Johnson');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the contact information for all married clients.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Marital_Status = 'Married';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average value of real estate assets?",
     'SQLQuery': "SELECT AVG(Value) FROM Financial_Assets WHERE Asset_Type = 'Real Estate';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members for clients with more than 2 dependents.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Dependents > 2);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total net worth of clients who are single.",
     'SQLQuery': "SELECT SUM(Net_Worth) FROM Client_Profile WHERE Marital_Status = 'Single';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the profession of Alok Desai.",
     'SQLQuery': "SELECT Profession FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Alok' WHERE TRIM(LOWER(Last_Name)) = 'Desai';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all investment portfolios for clients in Texas.",
     'SQLQuery': "SELECT * FROM Investment_Portfolio WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Texas');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many family members does John Doe have?",
     'SQLQuery': "SELECT COUNT(*) FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'John' WHERE TRIM(LOWER(Last_Name)) = 'Doe');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average amount of financial transactions for clients with a net worth over $1,000,000?",
     'SQLQuery': "SELECT AVG(Amount) FROM Financial_Transactions WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Net_Worth > 1000000);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total liabilities for clients living in New York.",
     'SQLQuery': "SELECT SUM(Amount) FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'New York');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the financial goals of clients with a net worth less than $500,000.",
     'SQLQuery': "SELECT Financial_Goals FROM Client_Profile WHERE Net_Worth < 500000;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients whose financial goal is to retire at 60.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Financial_Goals LIKE '%retire at 60%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of investments in technology?",
     'SQLQuery': "SELECT SUM(Amount) FROM Investment_Portfolio WHERE Investment_Type = 'Technology';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average number of dependents per client.",
     'SQLQuery': "SELECT AVG(Dependents) FROM Client_Profile;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the net worth of clients with more than 3 dependents.",
     'SQLQuery': "SELECT Net_Worth FROM Client_Profile WHERE Dependents > 3;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients living in California.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE State = 'California';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients whose financial goal includes 'travel'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Financial_Goals LIKE '%travel%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the value of the highest investment in real estate.",
     'SQLQuery': "SELECT MAX(Value) FROM Financial_Assets WHERE Asset_Type = 'Real Estate';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members of clients named 'Michael Williams'.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Michael' WHERE TRIM(LOWER(Last_Name)) = 'Williams');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many clients have a financial goal to save for their children's education?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Financial_Goals LIKE '%save for children%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average net worth of clients living in California.",
     'SQLQuery': "SELECT AVG(Net_Worth) FROM Client_Profile WHERE State = 'California';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the total value of all financial assets.",
     'SQLQuery': "SELECT SUM(Value) FROM Financial_Assets;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients whose profession is 'Engineer'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Profession = 'Engineer';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total number of family members for clients living in Texas?",
     'SQLQuery': "SELECT COUNT(*) FROM Family_Members WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Texas');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the client with the lowest net worth.",
     'SQLQuery': "SELECT * FROM Client_Profile ORDER BY Net_Worth ASC LIMIT 1;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the contact information of all clients living in California.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE State = 'California';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Retrieve the total number of dependents for clients who are married.",
     'SQLQuery': "SELECT SUM(Dependents) FROM Client_Profile WHERE Marital_Status = 'Married';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Give me the net worth of the client with the name 'Michael Williams'.",
     'SQLQuery': "SELECT Net_Worth FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Michael' WHERE TRIM(LOWER(Last_Name)) = 'Williams';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many dependents does Emily Johnson have?",
     'SQLQuery': "SELECT Dependents FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Emily' WHERE TRIM(LOWER(Last_Name)) = 'Johnson';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Who is Jane Smith's spouse?",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Family_Members WHERE Relationship = 'Spouse' AND ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Jane' WHERE TRIM(LOWER(Last_Name)) = 'Smith');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members of Michael Williams.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Michael' WHERE TRIM(LOWER(Last_Name)) = 'Williams');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of all assets for clients living in Texas?",
     'SQLQuery': "SELECT SUM(Value) FROM Financial_Assets WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Texas');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the contact information for clients with no dependents.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Dependents = 0;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average amount of liabilities for clients who are single?",
     'SQLQuery': "SELECT AVG(Amount) FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Marital_Status = 'Single');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all investment types held by John Doe.",
     'SQLQuery': "SELECT Investment_Type FROM Investment_Portfolio WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'John' WHERE TRIM(LOWER(Last_Name)) = 'Doe');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many transactions did Jane Smith make in 2022?",
     'SQLQuery': "SELECT COUNT(*) FROM Financial_Transactions WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Jane' WHERE TRIM(LOWER(Last_Name)) = 'Smith') AND Date BETWEEN '2022-01-01' AND '2022-12-31';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total net worth of all clients living in New York?",
     'SQLQuery': "SELECT SUM(Net_Worth) FROM Client_Profile WHERE State = 'New York';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients whose profession is 'Lawyer'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Profession = 'Lawyer';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the financial goals of Emily Johnson.",
     'SQLQuery': "SELECT Financial_Goals FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Emily' WHERE TRIM(LOWER(Last_Name)) = 'Johnson';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all financial assets of Jane Smith.",
     'SQLQuery': "SELECT * FROM Financial_Assets WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Jane' WHERE TRIM(LOWER(Last_Name)) = 'Smith');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many clients are married?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Marital_Status = 'Married';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of investments for clients living in North Carolina?",
     'SQLQuery': "SELECT SUM(Amount) FROM Investment_Portfolio WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'North Carolina');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients who have more than 1 dependent.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Dependents > 1;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the average net worth of clients living in Ohio.",
     'SQLQuery': "SELECT AVG(Net_Worth) FROM Client_Profile WHERE State = 'Ohio';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all liabilities for clients with a net worth less than $500,000.",
     'SQLQuery': "SELECT * FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Net_Worth < 500000);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total number of clients living in Texas?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE State = 'Texas';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all transactions for clients named 'John Doe'.",
     'SQLQuery': "SELECT * FROM Financial_Transactions WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'John' WHERE TRIM(LOWER(Last_Name)) = 'Doe');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the contact information for all clients who are single.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Marital_Status = 'Single';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average value of investment assets?",
     'SQLQuery': "SELECT AVG(Value) FROM Financial_Assets WHERE Asset_Type = 'Investment';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members for clients with more than 3 dependents.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Dependents > 3);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total net worth of clients who are married.",
     'SQLQuery': "SELECT SUM(Net_Worth) FROM Client_Profile WHERE Marital_Status = 'Married';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the profession of Jane Smith.",
     'SQLQuery': "SELECT Profession FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Jane' WHERE TRIM(LOWER(Last_Name)) = 'Smith';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all investment portfolios for clients in Ohio.",
     'SQLQuery': "SELECT * FROM Investment_Portfolio WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Ohio');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many family members does Jane Smith have?",
     'SQLQuery': "SELECT COUNT(*) FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Jane' WHERE TRIM(LOWER(Last_Name)) = 'Smith');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average amount of financial transactions for clients with a net worth less than $500,000?",
     'SQLQuery': "SELECT AVG(Amount) FROM Financial_Transactions WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Net_Worth < 500000);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total liabilities for clients living in California.",
     'SQLQuery': "SELECT SUM(Amount) FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'California');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the financial goals of clients with a net worth greater than $1,000,000.",
     'SQLQuery': "SELECT Financial_Goals FROM Client_Profile WHERE Net_Worth > 1000000;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients whose financial goal is to buy a house.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Financial_Goals LIKE '%buy a house%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total value of investments in healthcare?",
     'SQLQuery': "SELECT SUM(Amount) FROM Investment_Portfolio WHERE Investment_Type = 'Healthcare';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average number of dependents for clients living in New York.",
     'SQLQuery': "SELECT AVG(Dependents) FROM Client_Profile WHERE State = 'New York';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the net worth of clients with no financial liabilities.",
     'SQLQuery': "SELECT Net_Worth FROM Client_Profile WHERE ClientID NOT IN (SELECT DISTINCT ClientID FROM Financial_Liabilities);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients living in Florida.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE State = 'Florida';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find all clients whose financial goal includes 'investment'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Financial_Goals LIKE '%investment%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the value of the highest investment in stocks.",
     'SQLQuery': "SELECT MAX(Value) FROM Financial_Assets WHERE Asset_Type = 'Stocks';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all family members of clients named 'Emily Johnson'.",
     'SQLQuery': "SELECT * FROM Family_Members WHERE ClientID = (SELECT ClientID FROM Client_Profile WHERE TRIM(LOWER(First_Name)) = 'Emily' WHERE TRIM(LOWER(Last_Name)) = 'Johnson');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many clients have a financial goal to save for retirement?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Financial_Goals LIKE '%save for retirement%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average net worth of clients living in New York.",
     'SQLQuery': "SELECT AVG(Net_Worth) FROM Client_Profile WHERE State = 'New York';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the total value of all financial liabilities.",
     'SQLQuery': "SELECT SUM(Value) FROM Financial_Liabilities;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients whose profession is 'Teacher'.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Profession = 'Teacher';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total number of family members for clients living in Ohio?",
     'SQLQuery': "SELECT COUNT(*) FROM Family_Members WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Ohio');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total number of clients with a net worth over $2,000,000.",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Net_Worth > 2000000;",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the contact information of clients with a profession in the medical field.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Profession LIKE '%Doctor%' OR Profession LIKE '%Nurse%' OR Profession LIKE '%Medical%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average investment amount for clients with more than 1 dependent?",
     'SQLQuery': "SELECT AVG(Value) FROM Financial_Assets WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Dependents > 1);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all real estate assets for clients living in New York.",
     'SQLQuery': "SELECT * FROM Financial_Assets WHERE Asset_Type = 'Real Estate' AND ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'New York');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "How many clients have a financial goal to invest in stocks?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE Financial_Goals LIKE '%invest in stocks%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average net worth of clients living in Florida.",
     'SQLQuery': "SELECT AVG(Net_Worth) FROM Client_Profile WHERE State = 'Florida';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the total value of investments in real estate for clients living in California.",
     'SQLQuery': "SELECT SUM(Value) FROM Financial_Assets WHERE Asset_Type = 'Real Estate' AND ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'California');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "List all clients whose financial goal is to start a business.",
     'SQLQuery': "SELECT First_Name, Last_Name FROM Client_Profile WHERE Financial_Goals LIKE '%start a business%';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the total number of clients living in California?",
     'SQLQuery': "SELECT COUNT(*) FROM Client_Profile WHERE State = 'California';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the average number of financial transactions for clients who are single.",
     'SQLQuery': "SELECT AVG(Amount) FROM Financial_Transactions WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Marital_Status = 'Single');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Get the contact information for all clients who are engineers.",
     'SQLQuery': "SELECT First_Name, Last_Name, Contact_Information FROM Client_Profile WHERE Profession = 'Engineer';",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "What is the average value of liabilities for clients living in Texas?",
     'SQLQuery': "SELECT AVG(Value) FROM Financial_Liabilities WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE State = 'Texas');",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {'Question': "Find the total value of investments for clients with no dependents.",
     'SQLQuery': "SELECT SUM(Amount) FROM Investment_Portfolio WHERE ClientID IN (SELECT ClientID FROM Client_Profile WHERE Dependents = 0);",
     'SQLResult': "Result of the SQL query",
     'Answer': ""},
    {
        'Question': "What is the average Networth of each profession?",
        'SQLQuery': "SELECT Profession, AVG(NetWorth) AS AverageNetWorth FROM client_profile GROUP BY Profession;",
        'SQLResult':"Result of the SQL query",
        'Answer': """Entrepreneur	2500000.000000
                    Doctor 3000000.000000
                    Engineer 1950000.000000
                    Lawyer 3000000.000000
                    Software Dev 900000.000000
                    Accountant 1500000.000000
                    Doctor 3500000.000000
                    Artist 600000.000000
                    Consultant 2650000.000000
                    Business Exec 4000000.000000
                    Entrepreneur 2300000.000000
                    Nurse 800000.000000
                    Student 100000.000000
                    Marketing 1600000.000000
                    Writer 400000.000000
                    HR Manager 1900000.000000
                    Financial Adv 2500000.000000
                    Designer 700000.000000
                    Architect 2600000.000000"""
    },
    {
        'Question': "What is the name and client ID of all clients whose financial goals are to save for their children's future?",
        'SQLQuery': "SELECT ClientID, FirstName, LastName FROM client_profile WHERE FinancialGoals LIKE '%save for children''s education%';",
        'SQLResult':"Result of the SQL query",
        'Answer': """1 Alok Desai
                    4 Emily Johnson
                    9 Matthew Taylor
                    13 James Garcia
                    15 Benjamin Hill
                    19 Jackson Scott
                    21 William Green"""
    },
    {
        'Question': "What is the name and client ID of all clients who live in Texas and have no dependents?",
        'SQLQuery': "SELECT ClientID, FirstName, LastName FROM client_profile WHERE State = 'Texas' AND Dependents = 0;",
        'SQLResult':"Result of the SQL query",
        'Answer': "14 Sophia Hernandez"
    },
    {
        'Question': "What is the average neworth of all clients who are married doctors?",
        'SQLQuery': "SELECT AVG(NetWorth) AS AverageNetWorth FROM client_profile WHERE MaritalStatus = 'Married' AND Profession = 'Doctor';",
        'SQLResult':"Result of the SQL query",
        'Answer': "3000000.000000"
    },
    {
        'Question': "What is the name and client ID of all inactive clients?",
        'SQLQuery': "SELECT ClientID, FirstName, LastName FROM client_profile WHERE Status = 'prospect.warm' OR Status = 'prospect.cold';",
        'SQLResult':"Result of the SQL query",
        'Answer': """4 Emily Johnson
                    8 Jessica Martinez
                    11 Ethan Wilson
                    14 Sophia Hernandez
                    17 Alexander Perez
                    20 Amelia Evans"""
    },
    {
        'Question': "What is the name of all clients who have a child 18 or older as of 2024?",
        'SQLQuery': "SELECT c.FirstName, c.LastName FROM client_profile c JOIN familymembers fm ON c.ClientID = fm.ClientID WHERE fm.Relationship = 'Child' AND fm.DateOfBirth < '2006-01-01';",
        'SQLResult':"Result of the SQL query",
        'Answer': "Alok	Desai"
    },
    {
        'Question': "What is the client ID and networth of all divorced clients?",
        'SQLQuery': "SELECT ClientID, NetWorth FROM client_profile WHERE TRIM(MaritalStatus) = 'Divorced';",
        'SQLResult':"Result of the SQL query",
        'Answer': """6 1500000.00
                    10	4000000.00
                    18 1900000.00"""
    },
    {
        'Question': "What is the Client ID, networth, and financial goals of all clients with dependents?",
        'SQLQuery': "SELECT ClientID, FinancialGoals, NetWorth FROM client_profile WHERE Dependents >= 1;",
        'SQLResult':"Result of the SQL query",
        'Answer': """1 Save for children's education, retire at 60 2500000.00
                    2	Invest for retirement, travel extensively	3000000.00
                    4	Save for children's education, retire at 65	2800000.00
                    6	Save for retirement, pay off mortgage 	1500000.00
                    7	Invest in real estate, travel	3500000.00
                    9	Save for children's education, retire at 60	2000000.00
                    10	Travel, philanthropy	4000000.00
                    11	Expand business, save for retirement	2300000.00
                    13	Save for children's education, retire at 65  	2700000.00
                    15	Save for children's education, retire at 60	3200000.00
                    16	Invest in stocks, travel	1600000.00
                    18	Save for retirement, travel  	1900000.00
                    19	Invest in real estate, save for children's education	2500000.00
                    21	Save for children's education, retire at 65	2600000.00
                    22	Save for retirement, travel extensively	3300000.00"""
    },
    {
        'Question': "What do all married clients in New York do for work?",
        'SQLQuery': "SELECT Profession FROM client_profile WHERE TRIM(Marital_Status) = 'Single' AND State = 'New York';",
        'SQLResult':"Result of the SQL query",
        'Answer': """Software Dev
                    Designer"""
    },
    {
        'Question': "Can you give me the contact information of all clients with spouses as well as their spouses contact information?",
        'SQLQuery': "SELECT DISTINCT fm.Contact_Information FROM familymembers fm JOIN familymembers fm2 ON fm.ClientID = fm2.ClientID WHERE fm.Relationship = 'Spouse' OR (fm.Relationship = 'Self' AND fm2.Relationship = 'Self' AND fm.ClientID = fm2.ClientID);",
        'SQLResult':"Result of the SQL query",
        'Answer': """alok.desai@email.com
                    neha.desai@email.com
                    jane.smith@email.com
                    david.smith@email.com
                    michael.w@email.com       
                    matt.taylor@email.com     
                    rachel.t@email.com
                    ava.thomp@email.com       
                    ben.hill@email.com        
                    char.bailey@email.com     
                    will.green@email.com      
                    harper.m@email.com"""
    }
]
